### ISSUE TITLE
romans.shx rendered wrong

### ISSUE THREAD

**Issue by jshenguru** [pattern-x/gemini-viewer-examples#53] opened 2023-03-22 16:46 UTC
The following is how the romans.shx font looks like in AutoCAD

![AutoCAD_romans_shx](https://user-images.githubusercontent.com/26332171/226977645-96989508-df07-44b8-a81b-22f150172bd0.PNG)

The following is how the romans.shx font looks like in gemini-viewer-threejs

![gemini-viewer-threejs_romans_shx](https://user-images.githubusercontent.com/26332171/226977514-b1b6e57c-c2e5-4683-8b90-4295b7ff371e.PNG)

As can be seen in the gemini-viewer-threejs, the letter "C" is flipped vertically and the width of all characters are smaller than what they should be.

**Comment by pattern-x** [comment] 2023-03-23 02:11
Oh, unbeleivable! I'll ask my colleague to take a look when he has time...

**Comment by pattern-x** [comment] 2023-03-25 01:26
I cannot reproduce it, can you shell the dxf file?

**Comment by jshenguru** [comment] 2023-03-25 02:39
Here you go.

[Font_issue_1.zip](https://github.com/pattern-x/gemini-viewer-examples/files/11067817/Font_issue_1.zip)

To replicate the issue you will have to use the "romans.shx" from AutoCAD.

**Comment by pattern-x** [comment] 2023-03-26 01:33
Yeah, I can reproduce it now. There are two charactors "C" and "=" have this issue. Don't know the reason yet.

 ![image](https://user-images.githubusercontent.com/93636579/227750414-10b5911b-02cb-481e-b6ee-f8b18a670629.png)

**Comment by jshenguru** [comment] 2023-03-26 01:37
Please also note that the character is rendered narrower than expected. Please refer to the screenshots that I pasted in the beginning of this thread.

**Comment by Lisp1012** [comment] 2023-03-27 08:43
> Please also note that the character is rendered narrower than expected. Please refer to the screenshots that I pasted in the beginning of this thread.

Yes,we don't think that the web app needs to load many fonts, which will affect the loading performance. We think that the viewing side only needs to unify into one font for better viewing

**Comment by jshenguru** [comment] 2023-03-27 11:05
I am not talking about loading many fonts. What I am saying is that the "romans.shx", the only font file that I specified. That font is rendered narrower than expected. Any idea why?

**Comment by yanzexuan1** [comment] 2023-03-28 03:19
We can fix it for romans.shx. 

Font defines the graph of characters, width and height, distance between them. In this system, we mainly draw texts with lines rather than meshes. We changed the graph, we try not to affect its width, distances, etc. Pretty hard to keep their widht exactly the same as in acad.

**Comment by yanzexuan1** [comment] 2023-03-28 06:14
Fixed in https://github.com/pattern-x/gemini-viewer-examples/pull/69, can you check it out?

**Comment by yanzexuan1** [comment] 2023-03-31 02:18
> The following is how the romans.shx font looks like in AutoCAD
> 
> ![AutoCAD_romans_shx](https://user-images.githubusercontent.com/26332171/226977645-96989508-df07-44b8-a81b-22f150172bd0.PNG)
> 
> The following is how the romans.shx font looks like in gemini-viewer-threejs
> 
> ![gemini-viewer-threejs_romans_shx](https://user-images.githubusercontent.com/26332171/226977514-b1b6e57c-c2e5-4683-8b90-4295b7ff371e.PNG)
> 
> As can be seen in the gemini-viewer-threejs, the letter "C" is flipped vertically and the width of all characters are smaller than what they should be.

It's been fixed. Will be available in v0.2.31 release.

**Closed** 2023-04-10 15:06 UTC
